services:
  postgres:
    container_name: postgres
    platform: linux/amd64
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vcildb
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - $PWD/dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    mem_limit: 512m
    networks:
      - appnetwork

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
     - redis_volume:/data
    ports:
      - 6379:6379
    mem_limit: 96m
    networks:
      - appnetwork

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 3333:3333
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch

volumes:
  postgres_volume:
  redis_volume:

networks:
  appnetwork:
    driver: bridge
